name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Hugging Face repository ko remote ke taur par add karein
          git remote add hf https://mahmad995:$HF_TOKEN@huggingface.co/spaces/mahmad995/my-wifi-app
          
          # Hugging Face se changes pull karein taake conflicts na hon aur space meta files safe rahein
          git pull hf main --rebase || echo "No remote changes to rebase"
          
          # Ab track karke push karein bina data loss ke
          git push hf main
