name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Space
        # Yeh official plugin saari history aur git-lfs ke errors ko khud manage kar leta hai
        uses: Prime-S/sync-to-huggingface-space@v1.1
        with:
          shared-secret: ${{ secrets.HF_TOKEN }}
          hf-username: 'mahmad995'
          hf-space-name: 'my-wifi-app'
